# Generated by Django 5.2.1 on 2025-05-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="exchangeproposal",
            constraint=models.UniqueConstraint(
                fields=("ad_sender", "ad_receiver"), name="unique_exchange_pair"
            ),
        ),
    ]
